{{- define "deployment.tpl" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.def.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    {{- include "selectorLabels" . | nindent 4}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.def.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.labels" . | nindent 8 }}
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      {{- include "deploymentContainer.tpl" . | nindent 6 }}
      {{- with .Values.def.deployment.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8}}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.def.deployment.nodeSelector | nindent 8 }}
      {{- with .Values.def.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.def.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}

{{- if .Values.azure -}}
{{- include "render" (tuple . "deployment.tpl") -}}
{{- end -}}