{{- define "route.tpl" -}}
{{- range $ingressName, $ingress := .Values.def.ingresses -}}
{{- $isDefault := eq $ingressName "default" -}}
{{- $ingressName := (ternary $.Values.def.name (printf "%s-%s" $.Values.def.name $ingressName) $isDefault) -}}

{{- with  $ -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ $ingressName }}
  name: {{ $ingressName }}
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ $ingress.host }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: {{ .Values.def.name }}
  wildcardPolicy: None
---
{{ end -}}
{{- end -}}
{{- end -}}


{{- if not .Values.azure -}}
{{- include "render" (tuple . "route.tpl") -}}
{{- end -}}