#!/usr/bin/env python3
import os
from os.path import join
import shutil
import sqlite3
import subprocess
from types import SimpleNamespace


def _get_projects():
    query = '''select
    p.name,
    p.path,
    "base " || group_concat(e.name, " ")
from 
    project p 
    left join environment e on 
        (p.name = e.project) 

where
    p.github_access 
    and p.kind="api" 

group by p.name

limit 2'''

    dbfile = '/home/rmonico/.config/sdb/databases/migracaoaks.sqlite'

    with (connection := sqlite3.connect(dbfile)) as db:
        cursor = db.cursor()

        rs = cursor.execute(query)

        projects = list()

        cols = ['name', 'path', 'envs']

        for raw_row in rs:
            row = dict()

            for i, col in enumerate(cols):
                row[col] = raw_row[i]

            project = SimpleNamespace(**row)

            project.envs = project.envs.split(' ')

            projects.append(project)

        return projects


def run(*args):
    return subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def runstr(args):
    return subprocess.run(args.split(' '), stdout=subprocess.PIPE, stderr=subprocess.PIPE)


def rundecode(*args):
    return subprocess.run(args, stdout=subprocess.PIPE).stdout.decode()


def _remove_source_from_begin_of_file(path):
    oldpath = path + '.old'
    shutil.move(path, oldpath)

    with open(oldpath) as oldfile:
        with open(path, 'w') as newfile:
            for line in oldfile.readlines():
                if not line.startswith('# Source: '):
                   newfile.write(line)

    os.unlink(oldpath)


def _remove_source_from_begin_of_files(path):
    for obj in [join(path, o) for o in os.listdir(path)]:
        if os.path.isdir(obj):
            _remove_source_from_begin_of_files(obj)
        elif os.path.isfile(obj) and obj.endswith('.yaml'):
            _remove_source_from_begin_of_file(obj)


def main():
    projects = _get_projects()

    generatorfolder = os.getcwd()

    sourcefolder = join(generatorfolder, 'source')

    chartfolder = join(generatorfolder, 'output', 'mychart', 'templates', 'chart')

    valuesfile = join(chartfolder, 'values.yaml')
    chartfile = join(chartfolder, 'Chart.yaml')
    # criar
    # templatesdir = join(generatorfolder, 'templates')
    # viaopsfile = join(chartfolder, 'viaops.yaml')

    errors = dict()

    bold = rundecode('tput', 'bold')
    green = rundecode('tput', 'setaf', '10')
    red = rundecode('tput', 'setaf', '1')
    boldgreen = bold + green
    boldred = bold + red
    reset = rundecode('tput', 'sgr0')

    ok_str = f'\r[ {boldgreen}OK{reset} ]'
    err_str = f'\r[ {boldred}ER{reset} ]'

    commitcommand = 'git commit --message'.split(' ')
    commitcommand.append('feat(CMOB-2670): esteiras migradas')

    # breakpoint()
    for proj in projects:
        print(f'Migrating project "{proj.name}" ("{proj.path}")')

        if os.path.exists(sourcefolder):
            shutil.rmtree(sourcefolder)

        os.chdir(proj.path)

        runstr('git switch --detach master')

        shutil.copytree('kustomize', sourcefolder)

        runstr('git branch -D automigration')
        runstr('git branch automigration master')

        runstr('git worktree remove --force ../automigration')
        runstr('git worktree add ../automigration automigration')

        proj.path = os.path.realpath(join(proj.path + '/../automigration'))

        os.makedirs(join(proj.path, 'chart', 'overlays'), exist_ok=True)

        os.chdir(generatorfolder)

        if os.path.exists('errors'):
            shutil.rmtree('errors')

        for env in proj.envs:
            print(f'[   ]  {env}', end='')

            proc = run('./generate', proj.name, env)

            if proc.returncode != 0:
                print(err_str)
                errors.setdefault(proj.name, list()).append(env)

                errorsdir = join('errors', proj.name)
                os.makedirs(errorsdir, exist_ok=True)

                with open(join(errorsdir, env + '.out'), 'wb') as file:
                    file.write(proc.stdout)

                with open(join(errorsdir, env + '.err'), 'wb') as file:
                    file.write(proc.stderr)

                continue
            
            print(ok_str)

            destchart = join(proj.path, 'chart')

            if env == 'base':
                destvalues = join(destchart, 'values.yaml')
            else:
                destvalues = join(destchart, 'overlays', f'values-{env}.yaml')

            shutil.copyfile(valuesfile, destvalues)

            if env == 'base':
                destchartfile = join(destchart, 'Chart.yaml')
                shutil.copyfile(chartfile, destchartfile)

                # # criar
                # desttemplatesdir = join(destchart, 'templates')
                # shutil.copytree(templatesdir, desttemplatesdir)

                # # Pegar o nome correto do arquivo, yaml ou yml
                # destviaopsfile = join(destchart, '.github', 'workflows', 'viaops.yaml')
                # shutil.copyfile(viaopsfile, destviaopsfile)

        print()
        shutil.rmtree(sourcefolder)

        os.chdir(proj.path)

        _remove_source_from_begin_of_files(join(proj.path, 'chart'))

        runstr('git add -A')
        run(*commitcommand)
            

    if len(errors) > 0:
        print()
        print('Errors:')
        for proj, envs in errors.items():
            print(f'{proj}: {" ".join(envs)}')

if __name__ == '__main__':
    main()
