#!/usr/bin/bash

[[ "$#" -ne 2 || "$1" =~ --?h(elp)? ]] && {
    cat << EOF
$(basename $0) <project_name> <environment or "base">

Will generate chart/overlays/values-<env>.yaml based 

project_name    Name of project (ex: vv-adm)
environment     Environment name (ex: hlg)

"source" folder must be create (from project/kustomize)
EOF

    exit 0
}

project="$1"
envr="$2"

chart_path="$(dirname "$(realpath "$0")")"


if [ "$envr" == "base" ]; then
    ktmz_dir="base"
else
    ktmz_dir="overlays/$envr"
fi

echo "Chart path: \"$chart_path\""
echo "Kustomize dir: \"$ktmz_dir\""

if [ ! -d "source/$ktmz_dir" ]; then
    echo "Warn: environment \"$envr\" not found on project \"$project\""
    exit 0
fi

echo

helm template \
    --output-dir output \
    --set "app_name=$project,node_selector=vendemais,ktmz_dir=$ktmz_dir" \
    "$chart_path"
