#!/usr/bin/bash

chart_path="$(dirname "$(realpath "$0")")"
echo "Chart path: \"$chart_path\""

helm template \
    --output-dir output \
    --set 'app_name=vv-adm,node_selector=vendemais,base_path=base' \
    "$chart_path"
